export const meteo = {
	sunny : {weatherDescription: 'Soleil', iconUrl: 'weatherIcons/sunny.png'},
	lightRain :{ weatherDescription: 'Pluie légère', iconUrl: 'weatherIcons/rain.png' },
	rain :{ weatherDescription: 'Pluie', iconUrl: 'weatherIcons/rain.png' },
	strongRain :{ weatherDescription: 'Pluie forte', iconUrl: 'weatherIcons/rain.png' },
	cloudy :{ weatherDescription: 'Nuageux', iconUrl: 'weatherIcons/cloudy.png' },
	thunder :{ weatherDescription: 'Orages', iconUrl: 'weatherIcons/thunder.png' },
	lightSnow:{ weatherDescription: 'Neige modérée', iconUrl: 'weatherIcons/snow.png' },
	snow :{ weatherDescription: 'Neige', iconUrl: 'weatherIcons/snow.png' },
	strongSnow :{ weatherDescription: 'Neige forte', iconUrl: 'weatherIcons/snow.png' },
	hail :{ weatherDescription: 'Grêle', iconUrl: 'weatherIcons/rain.png' },
	rainAndSnow:{ weatherDescription: 'Pluie et neige', iconUrl: 'weatherIcons/rainandsnow.png' },
	fog:{ weatherDescription: 'Brouillard', iconUrl: 'weatherIcons/fog.png' },
	downpour :{ weatherDescription: 'Averse', iconUrl: 'weatherIcons/rain.png' },
	downpourSnow :{ weatherDescription: 'Averse de neige', iconUrl: 'weatherIcons/snow.png' },
};